### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by EricJeffrey** [1dooooo/hsup_sserpxe#1]
I encountered some problems when I tried to add timing task using crontab, and I think an update for the readme is needed.

1. it is better to mention that  [yourrootpath] need to be replaced
2. the bracket '()' inside `(*/30 * * * * python3 [yourrootpath]/main.py >> [yourrootpath]/out.log 2>&1)` should be removed, otherwise the crontab will fail
3. it is better to mention that the minitu configuration inside crontab command `*/30` should be either a single '*' or '30', meaning any time or 30 minutes
4. I believe it is also better to mention what crontab cmd will do, although one can learn it from manpage

**Comment by EricJeffrey** [comment]
btw, what is the php version used? and does it matter?

**Comment by 1dooooo** [comment]
> btw, what is the php version used? and does it matter?

maybe PHP version >5.3 is OK, I user 5.6 to work it.

**Comment by 1dooooo** [comment]
> I encountered some problems when I tried to add timing task using crontab, and I think an update for the readme is needed.
> 
> 1. it is better to mention that  [yourrootpath] need to be replaced
> 2. the bracket '()' inside `(*/30 * * * * python3 [yourrootpath]/main.py >> [yourrootpath]/out.log 2>&1)` should be removed, otherwise the crontab will fail
> 3. it is better to mention that the minitu configuration inside crontab command `*/30` should be either a single '*' or '30', meaning any time or 30 minutes
> 4. I believe it is also better to mention what crontab cmd will do, although one can learn it from manpage

you have given me the best issues I have ever seen at there.

**Comment by EricJeffrey** [comment]
> > btw, what is the php version used? and does it matter?
> 
> maybe PHP version >5.3 is OK, I user 5.6 to work it.

Got It
