### ISSUE TITLE
Open bug and way to fix -- wrapper

### ISSUE THREAD

**Issue by EricJeffrey** [1dooooo/hsup_sserpxe#3]
Well, it is clearly that checking file existence is needed for most `open()` calls (except those with mode para 'w'). what i'm thinking is make a wrapper for `open`, for example, `open_wrapper()` which has exactly the same para(or less, only paras needed) and same retval, but check file's existence first, then (create and) open it.

However i dont know if there is a better solution for it. So i'd like to know your opinion. and if it's ok, i may give a pr for it.

**Comment by oooood1** [comment]
Indeed, we should pay attention to your question. but there are some other problem raised if creat empty for one_phone_user , because it have no key in hes config.json file. it is just a example , I think your action should be more Comprehensive.

**Comment by oooood1** [comment]
> Well, it is clearly that checking file existence is needed for most `open()` calls (except those with mode para 'w'). what i'm thinking is make a wrapper for `open`, for example, `open_wrapper()` which has exactly the same para(or less, only paras needed) and same retval, but check file's existence first, then (create and) open it.
> 
> However i dont know if there is a better solution for it. So i'd like to know your opinion. and if it's ok, i may give a pr for it.

Indeed, we should pay attention to your question. but there are some other problem raised if creat empty for one_phone_user , because it have no key in hes config.json file. it is just a example , I think your action should be more Comprehensive.

**Comment by EricJeffrey** [comment]
i see, different things should be done if a file doesn't exist. well, guess i'll forget this.
